In [1]:
#Importing the required libraries
import pandas as pd
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
#Importing the csv file and only selecting "Class" and "ProcessedListing" column
df = pd.read_csv("Final_Processed.csv",usecols=["Class","ProcessedListings"])
df

Class  \
0                           Exterminator   
1            Handyman & General Services   
2                  Painting & Wall paper   
3                  Painting & Wall paper   
4    Installation, Repairs & Rennovation   
..                                   ...   
880        Caretaker/Personal Assisitant   
881            Housekeeping and Cleaning   
882                Painting & Wall paper   
883            Housekeeping and Cleaning   
884  Installation, Repairs & Rennovation   

                                     ProcessedListings  
0    inspect real 18month guarante extermin pestcon...  
1    home improv repair renov complet home repair r...  
2    painter grace paint remodel trumbul profession...  
3    painter grace paint remodel stamford room want...  
4    swing set instal instal playset today new york...  
..                                                 ...  
880  babysitt ni era pelham garden bx hi immatur wo...  
881  nyc best clean upper east side best clean serv...  
882  profession painter avail asap bronx yonker wes...  
883  organ housekeep 22 per hour soho organ houseke...  
884  furnitur assembl provid furnitur assembl move ...  

[885 rows x 2 columns]

In [3]:
#selecting feautures in X 
X = df.iloc[:,1].values
X

array(['inspect real 18month guarante extermin pestcontrol bx bk qn ny tri state transpar price licens extermin home inspect pest even bedbug boro certifi termit inspect roach treatment 125 room 3 famili hous 30day follow 18 month guarante bedbug 350 entir apt room follow 18 month guarante includ mous 125 entir apt 3 famili hous follow includ 18 month guarante handl pest gimmick charg per room contract sign servic set price plu follow guarante see get hidden fee extra cost match qout 18month guarante includ inspect servic come follow treatment ant bee mous rat tick flea fli moth spider roach bedbug cricket beetl wasp termit whatev organ kid pet peopl safe need leav home inhom inspect 24hr sameday servic avail violat remov commerci residenti servic avail veteran mo discount credit card accept gimmick hidden cost one set price includ follow guarante write one room price charg extra addit room contract gimmick thank competitor lock old websit tri get buy back old websit know best extermin

In [4]:
#storing the dependent variable in y
y = df.iloc[:,0].values
y

array(['Exterminator', 'Handyman & General Services',
       'Painting & Wall paper', 'Painting & Wall paper',
       'Installation, Repairs & Rennovation',
       'Installation, Repairs & Rennovation', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Others', 'Others',
       'Installation, Repairs & Rennovation',
       'Handyman & General Services', 'Flooring',
       'Housekeeping and Cleaning', 'Movers and Packers',
       'Movers and Packers', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Installation, Repairs & Rennovation',
       'Housekeeping and Cleaning', 'Handyman & General Services',
       'Painting & Wall paper', 'Painting & Wall paper',
       'Housekeeping and Cleaning', 'Handyman & General Services',
       'Handyman & General Services', 'Housekeeping and Cleaning',
       'Painting & Wall paper', 'Caretaker/Personal Assisitant',
       'Installation, Repairs & Renno

In [5]:
#Creating a tfidf vectorizer to transform processed listing into maxtrix form with minimum document frequency of 10 and including unigram and bigram words
tfidf = TfidfVectorizer(min_df=10,ngram_range=(1,2))
tfidf.fit(X)

TfidfVectorizer(min_df=10, ngram_range=(1, 2))

In [6]:
#Transforming the features in matrix form
X_transformed = tfidf.transform(X)
X_transformed = X_transformed.toarray()
X_transformed

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[("encoding",OneHotEncoder())],remainder = "passthrough")

In [8]:
y

array(['Exterminator', 'Handyman & General Services',
       'Painting & Wall paper', 'Painting & Wall paper',
       'Installation, Repairs & Rennovation',
       'Installation, Repairs & Rennovation', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Others', 'Others',
       'Installation, Repairs & Rennovation',
       'Handyman & General Services', 'Flooring',
       'Housekeeping and Cleaning', 'Movers and Packers',
       'Movers and Packers', 'Housekeeping and Cleaning',
       'Housekeeping and Cleaning', 'Installation, Repairs & Rennovation',
       'Housekeeping and Cleaning', 'Handyman & General Services',
       'Painting & Wall paper', 'Painting & Wall paper',
       'Housekeeping and Cleaning', 'Handyman & General Services',
       'Handyman & General Services', 'Housekeeping and Cleaning',
       'Painting & Wall paper', 'Caretaker/Personal Assisitant',
       'Installation, Repairs & Renno

In [9]:
#Tranforming the dependent variables into "One Hot" encoded form
#Label encoding the dependent variables and then tranforming it to one hot form using onehotencoder
le = LabelEncoder()
y_transformed = le.fit_transform(y)
onehotencoder = OneHotEncoder()
y_transformed = y_transformed.reshape(-1, 1)
y_transformed = onehotencoder.fit_transform(y_transformed).toarray()
y_transformed

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
#Splitting the data into traning set and test set 
x_train,x_test,y_train,y_test = train_test_split(X_transformed,y_transformed,test_size=0.2,random_state=1, stratify=y_transformed)

In [11]:
#Creting a sequential model
ann = tf.keras.models.Sequential()
#Input Layer with the number of neurons equal to the lenght of tensor in X_transformed
ann.add(tf.keras.layers.Dense(units = 3234, activation = "relu"))
#1st Hidden Layers with 6 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
#2nd Hidden Layers with 6 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
#Adding Dropout layer to reduce the chances of overfitting
ann.add(tf.keras.layers.Dropout(0.25))
#3rd Hidden Layers with 6 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
#4th Hidden Layers with 6 neurons and relu activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
#Output Layer with 9 neurons as we have 9 distinct categories in the dependent variable y
#Activation function is softmax as we are dealing with multiclass classification problem
ann.add(tf.keras.layers.Dense(units = 9, activation = "softmax"))

#Compiling the ann model with adam optimizer and loss function as categorical_crossentropy as its a multiclass(more than 2 classes) classification
ann.compile(optimizer = "adam",loss = "categorical_crossentropy", metrics= ["accuracy"] )
#Training the ANN with train data with a batch size of 32 and epochs 100
ann.fit(x_train,y_train,epochs=100,batch_size = 32)
#selecting the index position of the class with value 1 in the test data.
y_test_arg=np.argmax(y_test,axis=1)
#Making Predictions and selecting the index position of class with highest probability
Y_pred = np.argmax(ann.predict(x_test),axis=1)

Epoch 1/100
23/23 [==============================] - 2s 72ms/step - loss: 2.1771 - accuracy: 0.2811
Epoch 2/100
23/23 [==============================] - 2s 72ms/step - loss: 2.0901 - accuracy: 0.4379
Epoch 3/100
23/23 [==============================] - 2s 68ms/step - loss: 1.9830 - accuracy: 0.5113
Epoch 4/100
23/23 [==============================] - 2s 68ms/step - loss: 1.9209 - accuracy: 0.5297 0s - loss: 1.9238 - accuracy: 
Epoch 5/100
23/23 [==============================] - 2s 79ms/step - loss: 1.8546 - accuracy: 0.5268
Epoch 6/100
23/23 [==============================] - 2s 75ms/step - loss: 1.7836 - accuracy: 0.4661
Epoch 7/100
23/23 [==============================] - 1s 62ms/step - loss: 1.6694 - accuracy: 0.3150
Epoch 8/100
23/23 [==============================] - 1s 62ms/step - loss: 1.4303 - accuracy: 0.4605
Epoch 9/100
23/23 [==============================] - 1s 64ms/step - loss: 1.1963 - accuracy: 0.5523
Epoch 10/100
23/23 [==============================] - 1s 63ms/step - 

23/23 [==============================] - 1s 62ms/step - loss: 0.4581 - accuracy: 0.8277
Epoch 82/100
23/23 [==============================] - 1s 62ms/step - loss: 0.4656 - accuracy: 0.8333
Epoch 83/100
23/23 [==============================] - 1s 65ms/step - loss: 0.4951 - accuracy: 0.8107
Epoch 84/100
23/23 [==============================] - 2s 68ms/step - loss: 0.5065 - accuracy: 0.8121
Epoch 85/100
23/23 [==============================] - 1s 64ms/step - loss: 0.4927 - accuracy: 0.8121
Epoch 86/100
23/23 [==============================] - 1s 65ms/step - loss: 0.4738 - accuracy: 0.8277
Epoch 87/100
23/23 [==============================] - 1s 62ms/step - loss: 0.4908 - accuracy: 0.8150
Epoch 88/100
23/23 [==============================] - 1s 64ms/step - loss: 0.4768 - accuracy: 0.8164
Epoch 89/100
23/23 [==============================] - 2s 65ms/step - loss: 0.5354 - accuracy: 0.7994
Epoch 90/100
23/23 [==============================] - 2s 70ms/step - loss: 0.4885 - accuracy: 0.8136
Epo

In [13]:
#Printing the results using confusion matrix and accuracy score
print('Confusion Matrix')
print(confusion_matrix(y_test_arg, Y_pred))
print('Accuracy Score')
print(accuracy_score(y_test_arg, Y_pred))

Confusion Matrix
[[ 7  0  0  0  0  3  0  0  0]
 [ 0  3  0  0  0  1  0  0  0]
 [ 0  0  4  2  0  1  0  0  0]
 [ 1  0  0 21  1  0  0  1  0]
 [ 0  0  0  0 81  1  0  0  0]
 [ 0  1  0  1  0 18  0  0  0]
 [ 0  0  0  4  0  0  0  0  0]
 [ 1  0  1  3  6  0  0  4  0]
 [ 0  0  0 10  1  0  0  0  0]]
Accuracy Score
0.7796610169491526
